categories:
  - title: '⚙️ Build'
    label: 'build'
  - title: '🔄 CI'
    label: 'ci'
  - title: '📂 Documentation'
    label: 'documentation'
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐞 Bugfix'
    label: 'bugfix'
  - title: '📊 Performance improvements'
    label: 'performance'
  - title: '⚒️ Refactor'
    label: 'refactor'
  - title: '💅 Style'
    label: 'style'
  - title: '✅ Tests'
    label: 'tests'
autolabeler:
  - label: 'build'
    branch:
      - '/^build\/.+$/'
  - label: 'ci'
    branch:
      - '/^ci\/.+$/'
  - label: 'documentation'
    branch:
      - '/^docs?\/.+$/'
  - label: 'enhancement'
    branch:
      - '/^feat\/.+$/'
  - label: 'feature'
    branch:
      - '/^feat\/.+$/'
  - label: 'bugfix'
    branch:
      - '/^(fix|bugfix|hotfix)\/.+$/'
  - label: 'performance'
    branch:
      - '/^(perf|performance)\/.+$/'
  - label: 'refactor'
    branch:
      - '/^refactor\/.+$/'
  - label: 'style'
    branch:
      - '/^style\/.+$/'
  - label: 'test'
    branch:
      - '/^(test|tests)\/.+$/'
exclude-labels:
  - 'changelog'
change-template: '- $TITLE by @$AUTHOR in #$NUMBER'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## What's changed

  $CHANGES
