<?php

declare(strict_types=1);

namespace App\Replacers;

use App\Replacer;
use App\Replacers\Exceptions\InvalidEmail;
use Closure;
use Illuminate\Support\Str;
use Illuminate\Support\Stringable;

class EmailReplacer extends Builder
{
    protected static string $placeholder = 'email';

    public function __construct(string $replacement)
    {
        InvalidEmail::validate($replacement);

        parent::__construct($replacement);
    }

    protected function configure(Replacer $replacer): void
    {
        $replacer
            ->normalizeReplacementUsing(fn (Stringable $replacement) => $replacement->lower())
            ->onlyWith(['upper']);

        parent::configure($replacer); // TODO: Change the autogenerated stub
    }

    protected function modifiers(): array
    {
        return [
            'upper' => self::unwrapEmail(fn (Stringable $part) => $part->upper()),
        ];
    }

    protected static function unwrapEmail(Closure $both): Closure
    {
        return function (Stringable $replacement) use ($both): Stringable {
            [$localPart, $domain] = $replacement->explode('@')->map(fn ($part) => Str::of($part)->trim())->all();

            return Str::of('@')->trim()->wrap($both($localPart), $both($domain));
        };
    }
}
