<?php

namespace App\Replacers;

use App\Replacer;
use App\Replacers\Exceptions\InvalidVersion;
use Illuminate\Support\Str;
use Illuminate\Support\Stringable;

class VersionReplacer extends Builder
{
    public static string $placeholder = 'version';

    public function __construct(string $replacement)
    {
        InvalidVersion::validate($replacement);

        parent::__construct($replacement);
    }

    protected function configure(Replacer $replacer): void
    {
        $replacer->normalizeReplacementUsing(fn (Stringable $replacement) => $replacement);

        parent::configure($replacer); // TODO: Change the autogenerated stub
    }

    protected function modifiers(): array
    {
        $getSegment = function (Stringable $replacement, string $segment): Stringable {
            $pattern = InvalidVersion::$pattern;
            $matches = $replacement->matchAllWithGroups($pattern);

            return Str::of(($matches[0] ?? collect())->get($segment, $replacement));
        };

        return [
            'major' => fn (Stringable $replacement) => $getSegment($replacement, 'major'),
            'minor' => fn (Stringable $replacement) => $getSegment($replacement, 'minor'),
            'patch' => fn (Stringable $replacement) => $getSegment($replacement, 'patch'),
            'pre' => fn (Stringable $replacement) => $getSegment($replacement, 'prerelease'),
            'meta' => fn (Stringable $replacement) => $getSegment($replacement, 'buildmetadata'),
            'prefix' => fn (Stringable $replacement) => $replacement->prepend('v'),
        ];
    }

    protected function getExcludedModifiers(): array
    {
        return ['upper', 'lower', 'title', 'snake', 'kebab', 'camel', 'slug', 'acronym'];
    }
}
