name: Pull Request Labeler

on:
  pull_request_target:
    types: [opened, reopened]
    branches: [dev, main]

permissions:
  contents: read
  pull-requests: write

jobs:
  labeler:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/labeler@v6
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true
