name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Changelog
        uses: mikepenz/release-changelog-builder-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer

      - name: Install Dependencies
        run: composer install --no-dev --no-interaction --no-progress --optimize-autoloader

      - name: Build CLI
        run: php skeleton app:build --no-interaction --build-version="${{ github.ref_name }}" skeleton

      - name: Archive CLI
        run: |
          cd builds &&
          zip skeleton.zip skeleton &&
          tar -czf skeleton.tar.gz skeleton

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.github_release.outputs.changelog }}
          files: |
            builds/skeleton
            builds/skeleton.zip
            builds/skeleton.tar.gz
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
