name: Update Changelog

on:
  release:
    types: [released]

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    uses: coyotito-mx/.github/.github/workflows/update-changelog.yml@main
